{
 "title": "Backend Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "use_case", "label": "Use case", "query": { "query": "label_values(use_case)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "F1 Elo status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Use case success rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "downsampler": "mean", "expression": "($A * 100)/ ($A +$B)", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "Use case failure rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "downsampler": "mean", "expression": "($B * 100)/ ($A +$B)", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "Use case success executions",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(use_case) (increase(backend_f1elo_use_case_success_total[$__range]))",
     "legendFormat": "{{use_case}}"
    }
   ]
  },
  {
   "title": "HTTP Request latency per URI",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max",
     "legendFormat": "{{method}}::{{uri}}"
    }
   ]
  },
  {
   "title": "Use case execution time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_f1elo_use_case_execution_time_seconds_max",
     "legendFormat": "{{use_case}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Used RAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(__name__, area) (jvm_memory_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "disk_total_bytes", "legendFormat": "{{__name__}}" },
    {
     "expr": "disk_total_bytes - disk_free_bytes",
     "legendFormat": "disk used"
    }
   ]
  }
 ]
}