package com.barbzdev.sportselo.formulaone.domain.valueobject.race

enum class RaceResultStatus(val text: String) {
  FINISHED("Finished"),
  LAPS_1("+1 Lap"),
  LAPS_2("+2 Laps"),
  LAPS_3("+3 Laps"),
  LAPS_4("+4 Laps"),
  LAPS_5("+5 Laps"),
  LAPS_6("+6 Laps"),
  LAPS_7("+7 Laps"),
  LAPS_8("+8 Laps"),
  LAPS_9("+9 Laps"),
  DISQUALIFIED("Disqualified"),
  ACCIDENT("Accident"),
  ENGINE("Engine"),
  GEARBOX("Gearbox"),
  TRANSMISSION("Transmission"),
  CLUTCH("Clutch"),
  HYDRAULICS("Hydraulics"),
  ELECTRONICS("Electronics"),
  SUSPENSION("Suspension"),
  BRAKES("Brakes"),
  THROTTLE("Throttle"),
  DRIVESHAFT("Driveshaft"),
  TYRE("Tyre"),
  PUNCTURE("Puncture"),
  FUEL("Fuel"),
  OIL("Oil"),
  WATER("Water"),
  OVERHEATING("Overheating"),
  COLLISION("Collision"),
  SPIN("Spin"),
  RADIATOR("Radiator"),
  EXHAUST("Exhaust"),
  ELECTRICAL("Electrical"),
  MECHANICAL("Mechanical"),
  DAMAGE("Damage"),
  PNEUMATIC("Pneumatic"),
  SAFETY("Safety"),
  WITHDRAWN("Withdrawn"),
  NOT_CLASSIFIED("Not Classified"),
  DISQUALIFIED_PREVIOUS("Disqualified"),
  EXCLUDED("Excluded"),
  NOT_STARTED("Not Started"),
  RETIRED("Retired"),
  DNS("Did Not Start"),
  SUSPENDED("Suspended"),
  INJURY("Injury"),
  SPUN_OFF("Spun Off"),
  DIFFERENTIAL("Differential"),
  DRIVER_SEAT("Driver Seat"),
  UNKNOWN("Unknown");

  companion object {
    fun fromText(text: String): RaceResultStatus =
      RaceResultStatus.entries.firstOrNull { it.text.equals(text, ignoreCase = true) } ?: UNKNOWN
  }
}
